# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7764ad14b9a24e501a7fdfd39c12c159"
name = "product-survey"
handle = "product-survey"
application_url = "https://messenger-lock-newer-win.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ilkerstheme.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://messenger-lock-newer-win.trycloudflare.com/auth/callback",
  "https://messenger-lock-newer-win.trycloudflare.com/auth/shopify/callback",
  "https://messenger-lock-newer-win.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
